import * as path from "node:path";
import * as fsp from "node:fs/promises";

type Include = {
  file: string;
  label?: string;
  endLabel?: string;
  alwaysFirst?: true;
};

type IncludesJson = Array<Include>;

function getDuplicates(includes: IncludesJson): string[] {
  const map = includes.reduce<Record<string, number>>((m, inc) => {
    const count = m[inc.file] ?? 0;

    m[inc.file] = count + 1;

    return m;
  }, {});

  const entries = Object.entries(map);

  return entries.flatMap((e) => {
    if (e[1] !== 1) {
      return [e[0]];
    } else {
      return [];
    }
  });
}

function generateIncludesAsm(includesJson: IncludesJson): string {
  const duplicates = getDuplicates(includesJson);

  if (duplicates.length > 0) {
    throw new Error(`Duplicate includes: ${duplicates.join(",")}`);
  }

  const includesAsm = includesJson.flatMap((inc) => {
    const iasm: string[] = [".even"];
    if (inc.label) {
      iasm.push(`${inc.label}:`);
    }
    iasm.push(`.include "${inc.file}"`);
    if (inc.endLabel) {
      iasm.push(`${inc.endLabel}:`);
    }

    return iasm;
  });

  const includesAsmSrc = [
    `;; generated by: ${__filename}`,
    ...includesAsm,
  ].join("\n");

  return includesAsmSrc;
}

async function main(includesJsonPath: string, outputPath: string) {
  const includesJson = require(includesJsonPath) as IncludesJson;
  const includesAsmSrc = generateIncludesAsm(includesJson);

  await fsp.writeFile(outputPath, includesAsmSrc);

  console.log("wrote", outputPath);
}

if (require.main === module) {
  const [_tsNode, _generateIncludesAsmTs, includesJsonPath, outputPath] =
    process.argv;

  if (!includesJsonPath || !outputPath) {
    console.error(
      "usage: ts-node generateIncludesAsm.ts <includes-json-path> <output-path>"
    );
    process.exit(1);
  }

  main(path.resolve(includesJsonPath), path.resolve(outputPath))
    .then(() => console.log("done"))
    .catch((e) => console.error(e));
}

export { generateIncludesAsm };
export type { IncludesJson, Include };
