global_palette:
    .include "global.shared.palette.asm"

GLOBAL_PALETTE_TRANS = 0
GLOBAL_PALETTE_WHITE = 1
GLOBAL_PALETTE_LIGHT_GREY = 2
GLOBAL_PALETTE_DARK_GREY = 3
GLOBAL_PALETTE_YELLOW = 4
GLOBAL_PALETTE_LIGHT_ORANGE = 5
LOBAL_PALETTE_LIGHT_BLUE = 6
GLOBAL_PALETTE_MED_BLUE = 7
GLOBAL_PALETTE_BRIGHT_GREEN = 8
GLOBAL_PALETTE_MUTED_GREEN = 9
GLOBAL_PALETTE_LIGHT_PURPLE = 10
GLOBAL_PALETTE_BLACK = 11
GLOBAL_PALETTE_DARK_ORANGE = 12
GLOBAL_PALETTE_RED = 12
GLOBAL_PALETTE_DARK_BLUE = 13
GLOBAL_PALETTE_DARK_GREEN = 14
GLOBAL_PALETTE_DARK_PURPLE = 15

GLOBAL_PALETTE_MAX_HIGHLIGHT_INDEX = 11
GLOBAL_PALETTE_MAX_HIGHLIGHT_INDEX_UPPER_NIBBLE = GLOBAL_PALETTE_MAX_HIGHLIGHT_INDEX * 16
GLOBAL_PALETTE_MAX_HIGHLIGHT_INDEX_LOWER_NIBBLE = GLOBAL_PALETTE_MAX_HIGHLIGHT_INDEX