PUZZLE_SIZE_SMALL = 0
PUZZLE_SIZE_MEDIUM = 1
PUZZLE_SIZE_LARGE = 2

PUZZLE_SMALL_TILE_COUNT = 5
PUZZLE_MEDIUM_TILE_COUNT = 8
PUZZLE_LARGE_TILE_COUNT = 15


PUZZLE_ID_OFFSET = 0
PUZZLE_SIZE_OFFSET = PUZZLE_ID_OFFSET + 2
PUZZLE_WIN_FILL_COUNT_OFFSET = PUZZLE_SIZE_OFFSET + 1
PUZZLE_NAME_OFFSET = PUZZLE_WIN_FILL_COUNT_OFFSET + 1
PUZZLE_TILE_DATA_OFFSET = PUZZLE_NAME_OFFSET + 13

PUZZLE_SIZE_OF_ID = PUZZLE_SIZE_OFFSET - PUZZLE_ID_OFFSET

PUZZLE_SIZE_OF_META_DATA = PUZZLE_TILE_DATA_OFFSET
PUZZLE_SIZE_OF_SMALL_MEDIUM_TILE_DATA = 32 * 1
PUZZLE_SIZE_OF_LARGE_TILE_DATA = 32 * 4
PUZZLE_SIZE_OF_SMALL_MEDIUM_PUZZLE = PUZZLE_SIZE_OF_META_DATA + PUZZLE_SIZE_OF_SMALL_MEDIUM_TILE_DATA
PUZZLE_SIZE_OF_LARGE_PUZZLE = PUZZLE_SIZE_OF_META_DATA + PUZZLE_SIZE_OF_LARGE_TILE_DATA