PUZZLE_COLLECTION_FUNCTION_POINTER_OFFSET = 0
PUZZLE_COLLECTION_PALETTE_OFFSET = PUZZLE_COLLECTION_FUNCTION_POINTER_OFFSET + 2
PUZZLE_COLLECTION_MASCOT_BODY_OFFSET = PUZZLE_COLLECTION_PALETTE_OFFSET + 32
PUZZLE_COLLECTION_MASCOT_SAD_FACE_OFFSET = PUZZLE_COLLECTION_MASCOT_BODY_OFFSET + 32 * 9
PUZZLE_COLLECTION_MASCOT_TAIL_OFFSET = PUZZLE_COLLECTION_MASCOT_SAD_FACE_OFFSET + 32 * 1
PUZZLE_COLLECTION_BG_ID_OFFSET = PUZZLE_COLLECTION_MASCOT_TAIL_OFFSET + 32 * 2
PUZZLE_COLLECTION_BGM_ID_OFFSET = PUZZLE_COLLECTION_BG_ID_OFFSET + 1
PUZZLE_COLLECTION_PUZZLE_COUNT_OFFSET = PUZZLE_COLLECTION_BGM_ID_OFFSET + 2
PUZZLE_COLLECTION_PUZZLES_OFFSET = PUZZLE_COLLECTION_PUZZLE_COUNT_OFFSET + 1

PUZZLE_COLLECTION_MAX_PUZZLES = 20